# Useless
# Copyright (C) 2022 KuuhakuTeam
#
# This file is a part of < https://github.com/KuuhakuTeam/Useless/ >
# PLease read the GNU v3.0 License Agreement in
# <https://www.github.com/KuuhakuTeam/Useless/blob/master/LICENSE/>.

import random

from gpytranslate import Translator
from apscheduler.schedulers.asyncio import AsyncIOScheduler

from pyrogram import filters
from pyrogram.enums import ChatType
from pyrogram.errors import ChatIdInvalid, ChatWriteForbidden, ChannelInvalid, ChannelPrivate, PeerIdInvalid
from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton, CallbackQuery


from useless import useless, trg
from useless.helpers import db, check_rights, Groups


DB = db("GROUPS")
API = "https://uselessfacts.jsph.pl/random.json?language=en"

scheduler = AsyncIOScheduler()


@useless.on_message(filters.command(["start"], trg))
async def starting(_, message):
    keyboard = InlineKeyboardMarkup(
        [
            [
                InlineKeyboardButton(
                    text="Repository", url=f"https://github.com/KuuhakuTeam/Useless/",
                ),
                InlineKeyboardButton(
                    text="Add to a group", url=f"https://t.me/{useless.me.username}?startgroup=new",
                ),
            ],
        ]
    )
    if message.chat.type == ChatType.PRIVATE:
        await useless.send_photo(message.chat.id, "https://telegra.ph/file/2ce17b14b27631a05a113.png", caption=random.choice(RANDOM), reply_markup=keyboard)
    else:
        msg = "<b>/addchat - to add chat to bot info list\n/lang - to set the information language\n/stop - to stop receiving messages from me here.</b>"
        await message.reply(msg)


@useless.on_message(filters.command("addchat", trg))
async def add_to_list(_, message):
    chat_id = message.chat.id
    if not message.chat.type == ChatType.SUPERGROUP:
        return
    if not await check_rights(message.chat.id, message.from_user.id):
        return await message.reply("<i>You need to be admin to do this.</i>")
    if await Groups.find_gp(chat_id):
        await message.reply("<i>The chat is already on the useless list.</i>")
    else:
        await Groups.add_gp(message)
        await message.reply("<i>Chat has been added to useless list</i>")


@useless.on_message(filters.command("lang", trg))
async def set_lang_(_, message):
    chat_id = message.chat.id
    if not message.chat.type == ChatType.SUPERGROUP:
        return
    if not await check_rights(message.chat.id, message.from_user.id):
        return await message.reply("<i>You need to be admin to do this.</i>")
    if not await Groups.find_gp(chat_id):
        await message.reply("<i>This chat is not on the useless list, use /addchat to add.</i>")
    else:
        buttons_ = InlineKeyboardMarkup(
            [
                [
                    InlineKeyboardButton(
                        "🇧🇷 Português", callback_data=f"_lang|pt"),
                    InlineKeyboardButton(
                        "🇺🇸 English", callback_data=f"_lang|en")
                ],
            ]
        )
        await message.reply("<i>Select language in which you want to receive information</i>", reply_markup=buttons_)


@useless.on_callback_query(filters.regex(pattern=r"^_lang\|(.*)"))
async def set_language(_, cb: CallbackQuery):
    data, lang = cb.data.split("|")
    gid = cb.message.chat.id
    if cb.message.chat.type == ChatType.SUPERGROUP:
        if not await check_rights(gid, cb.from_user.id):
            return await cb.answer("You need to be admin to do this", show_alert=True)
    if lang == "pt":
        await Groups.add_lang(gid, "pt")
    else:
        await Groups.add_lang(gid, "en")
    await cb.edit_message_text(f"Information will be sent in {lang}")


@useless.on_message(filters.command("delchat", trg))
async def stop_infos(_, message):
    chat_id = message.chat.id
    if not message.chat.type == ChatType.SUPERGROUP:
        return
    if not await check_rights(message.chat.id, message.from_user.id):
        return await message.reply("<i>You need to be admin to do this.</i>")
    if await Groups.find_gp(chat_id):
        await Groups.rm_gp(chat_id)
        await message.reply("<i>Okay, I won't send messages here anymore.</i>")
    else:
        await message.reply("<i>This chat is not on the useless list.</i>")


async def info():
    glist = DB.find()
    async for chats in glist:
        if chats == None:
            return
        else:
            gid = chats["_id"]
            msg = rand_msg()
            lang = await Groups.find_lang(gid)
            if lang == "pt":
                tr = Translator()
                tr_ = await tr.translate(msg, targetlang="pt")
                msg = tr_.text
            try:
                await useless.send_message(chat_id=gid, text=msg)
            except (ChatIdInvalid, ChannelInvalid, ChannelPrivate, PeerIdInvalid):
                await Groups.rm_gp(gid)
                pass
            except (ChatWriteForbidden):
                await useless.leave(gid)
                await Groups.rm_gp(gid)
                pass
            except Exception as e:
                await useless.send_log(e, disable_notification=False, disable_web_page_preview=True)
                await useless.leave(gid)
                await Groups.rm_gp(gid)
                pass


def rand_msg():
    infos = {
        "lista": [
            "It is impossible to lick your elbow. ",
            "Intelligent people have more zinc and copper in their hair.",
            "In every episode of Seinfeld there is a Superman somewhere.",
            "Wearing headphones for just an hour will increase the bacteria in your ear by 700 times. ",
            "More than 50% of the people in the world have never made or received a telephone call. ",
            "13% of Americans actually believe that some parts of the moon are made of cheese.",
            "The world's youngest parents were 8 and 9 and lived in China in 1910.",
            "Fish that live more than 800 meters below the ocean surface don't have eyes.",
            "Grapes explode when you put them in the microwave. Go on, try it then",
            "Ramses brand condom is named after the great pharaoh Ramses II who fathered over 160 children. ",
            "Peanuts are one of the ingredients of dynamite.",
            "The average chocolate bar has 8 insects' legs in it.",
            "In York, it is perfectly legal to shoot a Scotsman with a bow and arrow (except on Sundays)",
            "No piece of square dry paper can be folded in half more than 7 times",
            "The average human eats 8 spiders in their lifetime at night. ",
            "\"Stewardesses\" is the longest word typed with only the left hand.",
            "An average human loses about 200 head hairs per day. ",
            "Mexico City sinks about 10 inches a year",
            "It's impossible to sneeze with your eyes open.",
            "In France, a five year old child can buy an alcoholic drink in a bar",
            "During the chariot scene in \"Ben Hur,\" a small red car can be seen in the distance.",
            "Because metal was scarce, the Oscars given out during World War II were made of wood.",
            "By raising your legs slowly and lying on your back, you cannot sink into quicksand. ",
            "Venus is the only planet that rotates clockwise.",
            "Charlie Chaplin once won third prize in a Charlie Chaplin look-alike contest.",
            "The glue on Israeli postage is certified kosher.",
            "In 10 minutes, a hurricane releases more energy than all of the world's nuclear weapons combined. ",
            "On average, 100 people choke to death on ball-point pens every year. ",
            "Thirty-five percent of the people who use personal ads for dating are already married. ",
            "The electric chair was invented by a dentist. ",
            "Bruce Lee was so fast that they actually had to s-l-o-w film down so you could see his moves. ",
            "A Boeing 747s wingspan is longer than the Wright brother's first flight.",
            "Babies are born without knee caps. They don't appear until the child reaches 2-6 years of age.",
            "14% of all facts and statistics are made up and 27% of people know that fact.",
            "Every time you lick a stamp, you're consuming 1/10 of a calorie.",
            "Eskimos have over 15 words for the English word of 'Snow'",
            "Americans on the average eat 18 acres of pizza every day.",
            "Banging your head against a wall uses 150 calories an hour.",
            "On a Canadian two dollar bill, the flag flying over the Parliament buildings is an American flag.",
            "Almonds are a member of the peach family.",
            "The plastic things on the end of shoelaces are called aglets.",
            "“Ithyphallophobia\" is a morbid fear of seeing, thinking about or having an erect penis.",
            "The average shelf-life of a latex condom is about two years. ",
            "14% of Americans have skinny-dipped with a member of the opposite sex at least once.",
            "Male bats have the highest rate of homosexuality of any mammal. ",
            "A man's beard grows fastest when he anticipates sex. ",
            "A man will ejaculate approximately 18 quarts of semen in his lifetime. ",
            "Sex is biochemically no different from eating large quantities of chocolate.",
            "Humans and dolphins are the only species that have sex for pleasure. ",
            "For every 'normal' webpage, there are five porn pages. ",
            "\"Venus observa\" is the technical term for the \"missionary position.\"",
            "Sex is the safest tranquilizer in the world. IT IS 10 TIMES MORE EFFECTIVE THAN VALIUM.",
            "Samuel Clemens (Mark Twain) was born on and died on days when Halley’s Comet can be seen. ",
            "US Dollar bills are made out of cotton and linen.",
            "The 57 on the Heinz ketchup bottle represents the number of pickle types the company once had.",
            "Americans are responsible for about 1/5 of the world’s garbage annually.",
            "Giraffes and rats can last longer without water than camels.",
            "Your stomach produces a new layer of mucus every two weeks so that it doesn’t digest itself.",
            "98% of all murders and rapes are by a close family member or friend of the victim.",
            "A B-25 bomber crashed into the 79th floor of the Empire State Building on July 28, 1945.",
            "The Declaration of Independence was written on hemp (marijuana) paper.",
            "The dot over the letter “i” is called a tittle.",
            "Benjamin Franklin was the fifth in a series of the youngest son of the youngest son.",
            "Triskaidekaphobia means fear of the number 13. ",
            "Paraskevidekatriaphobia means fear of Friday the 13th, which occurs one to three times a year. ",
            "In Italy, 17 is considered an unlucky number. In Japan, 4 is considered an unlucky number.",
            "A female ferret will die if it goes into heat and cannot find a mate.",
            "In ancient Rome, when a man testified in court he would swear on his testicles.",
            "The ZIP in “ZIP code” means Zoning Improvement Plan.",
            "Coca-Cola contained Coca (whose active ingredient is cocaine) from 1885 to 1903.",
            "A “2 by 4\" is really 1 1/2 by 3 1/2.",
            "It’s estimated that at any one time around 0.7% of the world’s population is drunk.",
            "40% of McDonald’s profits come from the sales of Happy Meals.",
            "Every person, including identical twins, has a unique eye & tongue print along with their finger print.",
            "The “spot” on the 7-Up logo comes from its inventor who had red eyes. He was an albino.",
            "315 entries in Webster’s 1996 dictionary were misspelled.",
            "The “save” icon in Microsoft Office programs shows a floppy disk with the shutter on backwards.",
            "Albert Einstein and Charles Darwin both married their first cousins ",
            "Camel’s have three eyelids.",
            "On average, 12 newborns will be given to the wrong parents every day.",
            "John Wilkes Booth’s brother once saved the life of Abraham Lincoln’s son.",
            "Warren Beatty and Shirley McLaine are brother and sister.",
            "Chocolate can kill dogs; it directly affects their heart and nervous system.",
            "Daniel Boone hated coonskin caps.",
            "55.1% of all US prisoners are in prison for drug offenses.",
            "Most lipstick contains fish scales.",
            "Dr. Seuss pronounced his name “soyce”.",
            "Slugs have four noses.",
            "Ketchup was sold in the 1830s as medicine.",
            "India has a Bill of Rights for cows.",
            "American Airlines saved $40,000 in 1987 by taking out an olive from First Class salads.",
            "About 200,000,000 M&Ms are sold each day in the United States.",
            "Because metal was scarce, the Oscars given out during World War II were made of wood.",
            "There are 318,979,564,000 possible combinations of the first four moves in Chess.",
            "There are no clocks in Las Vegas gambling casinos.",
            "Coconuts kill about 150 people each year. That’s more than sharks.",
            "Half of all bank robberies take place on a Friday.",
            "The name Wendy was made up for the book Peter Pan. There was never a recorded Wendy before it.",
            "The international telephone dialing code for Antarctica is 672.",
            "The first bomb the Allies dropped on Berlin in WWII killed the only elephant in the Berlin Zoo.",
            "The average raindrop falls at 7 miles per hour.",
            "If you put a drop of liquor on a scorpion, it will instantly go mad and sting itself to death.",
            "Bruce Lee was so fast that they had to slow the film down so you could see his moves.",
            "The first CD pressed in the US was Bruce Springsteen’s “Born in the USA”.",
            "IBM’s motto is “Think”. Apple later made their motto “Think different”.",
            "The original name for butterfly was flutterby.",
            "One in fourteen women in America is a natural blonde. Only one in sixteen men is.",
            "The Olympic was the sister ship of the Titanic, and she provided twenty-five years of service.",
            "When the Titanic sank, 2228 people were on it. Only 706 survived.",
            "Every day, 7% of the US eats at McDonald’s.",
            "During his entire life, Vincent Van Gogh sold exactly one painting, “Red Vineyard at Arles”.",
            "By raising your legs slowly and lying on your back, you cannot sink into quicksand.",
            "One in ten people live on an island.",
            "It takes more calories to eat a piece of celery than the celery has in it to begin with.",
            "28% of Africa is classified as wilderness. In North America, its 38%.",
            "Charlie Chaplin once won third prize in a Charlie Chaplin look-alike contest.",
            "Chewing gum while peeling onions will keep you from crying.",
            "Sherlock Holmes NEVER said “Elementary, my dear Watson”",
            "Humphrey Bogart NEVER said “Play it again, Sam” in Casablanca",
            "They NEVER said “Beam me up, Scotty” on Star Trek.",
            "Sharon Stone was the first Star Search spokes model.",
            "More people are afraid of open spaces (kenophobia) than of tight spaces (claustrophobia).",
            "The glue on Israeli postage is certified kosher.",
            "There is a 1 in 4 chance that New York will have a white Christmas.",
            "The Guinness Book of Records holds the record for being the book most often stolen from Libraries.",
            "Thirty-five percent of the people who use personal ads for dating are already married.",
            "$203,000,000 is spent on barbed wire each year in the U.S.",
            "Every US president has worn glasses (just not always in public).",
            "Bats always turn left when exiting a cave.",
            "Jim Henson first coined the word “Muppet”. It is a combination of “marionette” and “puppet.”",
            "The Michelin man is known as Mr. Bib. His name was Bibendum in the company’s first ads in 1896.",
            "The word “lethologica” describes the state of not being able to remember the word you want.",
            "About 14% of injecting drug users are HIV positive.",
            "A word or sentence that is the same front and back (racecar, kayak) is called a “palindrome”.",
            "A snail can sleep for 3 years.",
            "People photocopying their buttocks are the cause of 23% of all photocopier faults worldwide.",
            "China has more English speakers than the United States.",
            "One in every 9000 people is an albino.",
            "The electric chair was invented by a dentist.",
            "You share your birthday with at least 9 million other people in the world.",
            "Everyday, more money is printed for Monopoly sets than for the U.S. Treasury.",
            "Every year 4 people in the UK die putting their trousers on.",
            "Cats have over one hundred vocal sounds; dogs only have about ten.",
            "Our eyes are always the same size from birth but our nose and ears never stop growing.",
            "In every episode of “Seinfeld” there is a Superman picture or reference somewhere.",
            "Rats multiply so quickly that in 18 months, two rats could have over million descendants.",
            "Wearing headphones for just an hour will increase the bacteria in your ear by 700 times.",
            "Each year in America there are about 300,000 deaths that can be attributed to obesity.",
            "About 55% of all movies are rated R.",
            "About 500 movies are made in the US and 800 in India annually.",
            "Arabic numerals are not really Arabic; they were created in India.",
            "The February of 1865 is the only month in recorded history not to have a full moon.",
            "There is actually no danger in swimming right after you eat, though it may feel uncomfortable.",
            "The cruise liner Queen Elizabeth II moves only six inches for each gallon of diesel that it burns.",
            "More than 50% of the people in the world have never made or received a telephone call.",
            "A shark is the only fish that can blink with both eyes.",
            "There are about 2 chickens for every human in the world.",
            "The word “maverick” came into use after Samuel Maverick, a Texan refused to brand his cattle. ",
            "Two-thirds of the world’s eggplant is grown in New Jersey.",
            "On a Canadian two-dollar bill, the American flag is flying over the Parliament Building.",
            "An American urologist bought Napoleon’s penis for $40,000.",
            "No word in the English language rhymes with month, orange, silver, or purple.",
            "Dreamt is the only English word that ends in the letters “MT”.",
            "$283,200 is the absolute highest amount of money you can win on Jeopardy.",
            "Almonds are members of the peach family.",
            "Rats and horses can’t vomit.",
            "The penguin is the only bird that can’t fly but can swim.",
            "There are approximately 100 million acts of sexual intercourse each day.",
            "Winston Churchill was born in a ladies room during a dance.",
            "Maine is the only state whose name is just one syllable.",
            "Americans on average eat 18 acres of pizza every day.",
            "Every time you lick a stamp you consume 1/10 of a calorie.",
            "You are more likely to be killed by a champagne cork than by a poisonous spider.",
            "Hedenophobic means fear of pleasure.",
            "Ancient Egyptian priests would pluck every hair from their bodies.",
            "A crocodile cannot stick its tongue out.",
            "80% of burglaries are committed by people aged 13-21.",
            "An ant always falls over on its right side when intoxicated.",
            "All polar bears are left-handed.",
            "The catfish has over 27000 taste buds (more than any other animal)",
            "A cockroach will live nine days without its head before it starves to death.",
            "Butterflies taste with their feet.",
            "Elephants are the only mammals that cannot jump.",
            "An ostrich’s eye is bigger than its brain.",
            "Starfish have no brains.",
            "11% of the world is left-handed.",
            "Rubber bands last longer when refrigerated.",
            "The national anthem of Greece has 158 verses.",
            "There are 293 ways to make change for a dollar.",
            "A healthy (non-colorblind) human eye can distinguish between 500 shades of gray.",
            "A pregnant goldfish is called a twit.",
            "Lizards can self-amputate their tails for protection. It grows back after a few months.",
            "Los Angeles’ full name is “El Pueblo de Nuestra Senora la Reina de los Angeles de Porciuncula”. ",
            "A cat has 32 muscles in each ear.",
            "A honeybee can fly at fifteen miles per hour.",
            "Tigers have striped skin, not just striped fur.",
            "A “jiffy” is the scientific name for 1/100th of a second.",
            "The average child recognizes over 200 company logos by the time he enters first grade.",
            "The youngest pope ever was 11 years old.",
            "The first novel ever written on a typewriter is Tom Sawyer.",
            "One out of every 43 prisoners escapes from jail. 94% are recaptured.",
            "The average chocolate bar has 8 insects’ legs melted into it.",
            "A rhinoceros horn is made of compacted hair.",
            "Elwood Edwards did the voice for the AOL sound files (i.e. “You’ve got Mail!”).",
            "A polar bears skin is black. Its fur is actually clear, but like snow it appears white.",
            "Elvis had a twin brother named Garon, who died at birth, which is why Elvis middle name was Aron.",
            "\\xa0Dueling is legal in Paraguay as long as both parties are registered blood donors.",
            "Donkeys kill more people than plane crashes.",
            "Shakespeare invented the words “assassination” and “bump.”",
            "There are a million ants for every person on Earth.",
            "If you keep a goldfish in the dark room, it will eventually turn white.",
            "Women blink nearly twice as much as men.",
            "The name Jeep comes from “GP”, the army abbreviation for General Purpose.",
            "Right handed people live, on average, nine years longer than left handed people do.",
            "There are two credit cards for every person in the United States.",
            "Cats’ urine glows under a black light.",
            "A “quidnunc” is a person who is eager to know the latest news and gossip.",
            "Leonardo Da Vinci invented the scissors, the helicopter, and many other present day items.",
            "In the last 4000 years no new animals have been domesticated.",
            "25% of a human’s bones are in its feet.",
            "On average, 100 people choke to death on ballpoint pens every year.",
            "“Canada” is an Indian word meaning “Big Village”.",
            "Only one in two billion people will live to be 116 or older.",
            "Rape is reported every six minutes in the U.S.",
            "The human heart creates enough pressure in the bloodstream to squirt blood 30 feet.",
            "A jellyfish is 95% water.",
            "Truck driving is the most dangerous occupation by accidental deaths (799 in 2001).",
            "Banging your head against a wall uses 150 calories an hour.",
            "Elephants only sleep for two hours each day.",
            "On average people fear spiders more than they do death.",
            "The strongest muscle in the human body is the tongue. (the heart is not a muscle)",
            "In golf, a ‘Bo Derek’ is a score of 10.",
            "In the U.S, Frisbees outsell footballs, baseballs and basketballs combined.",
            "In most watch advertisements the time displayed on a watch is 10:10.",
            "If you plant an apple seed, it is almost guaranteed to grow a tree of a different type of apple.",
            "Al Capone’s business card said he was a used furniture dealer.",
            "The only real person to be a PEZ head was Betsy Ross.",
            "There are about 450 types of cheese in the world. 240 come from France.",
            "A dragonfly has a lifespan of 24 hours.",
            "In Iceland, a Big Mac costs $5.50.",
            "Broccoli and cauliflower are the only vegetables that are flowers.",
            "There is no solid proof of who built the Taj Mahal.",
            "In a survey of 200000 ostriches over 80 years, not one tried to bury its head in the sand.",
            "A dime has 118 ridges around the edge. A quarter has 119.",
            "”Judge Judy” has a $25,000,000 salary, while Supreme Court Justice Ginsberg has a $190,100 salary.",
            "Andorra, a tiny country between France & Spain, has the longest average lifespan: 83.49 years.",
            "Mr. Rogers was an ordained Presbyterian minister.",
            "In America you will see an average of 500 advertisements a day.",
            "John Lennon’s first girlfriend was named Thelma Pickles.",
            "You can lead a cow upstairs but not downstairs.",
            "The average person falls asleep in seven minutes.",
            "“The sixth sick sheik’s sixth sheep’s sick” is said to be the toughest tongue twister in English.",
            "There are 336 dimples on a regulation US golf ball. In the UK its 330.",
            "“Duff” is the decaying organic matter found on a forest floor.",
            "The US has more personal computers than the next 7 countries combined.",
            "Kuwait is about 60% male (highest in the world). Latvia is about 54% female (highest in the world).",
            "The Hawaiian alphabet has only 12 letters.",
            "In 10 minutes, a hurricane releases more energy than all the world’s nuclear weapons combined.",
            "At the height of its power in 400 BC, the Greek city of Sparta had 25,000 citizens and 500,000 slaves.",
            "Julius Caesar’s autograph is worth about $2,000,000.",
            "People say “bless you” when you sneeze because your heart stops for a millisecond.",
            "US gold coins used to say “In Gold We Trust”.",
            "In “Silence of the Lambs”, Hannibal Lector (Anthony Hopkins) never blinks.",
            "A shrimp’s heart is in its head.",
            "In the 17th century, the value of pi was known to 35 decimal places. Today, to 1.2411 trillion.",
            "Pearls melt in vinegar.",
            "“Lassie” was played by a group of male dogs; the main one was named Pal.",
            "Nepal is the only country that doesn’t have a rectangular flag. ",
            "Switzerland is the only country with a square flag.",
            "Gabriel, Michael, and Lucifer are the only angels named in the Bible.",
            "Johnny Appleseed planted apples so that people could use apple cider to make alcohol.",
            "Abraham Lincoln’s ghost is said to haunt the White House.",
            "God is not mentioned once in the book of Esther.",
            "The odds of being born male are about 51.2%, according to census.",
            "Scotland has more redheads than any other part of the world.",
            "There is an average of 61,000 people airborne over the US at any given moment.",
            "Prince Charles and Prince William never travel on the same airplane in case there is a crash.",
            "The most popular first name in the world is Muhammad. ",
            "The surface of the Earth is about 60% water and 10% ice.",
            "For every 230 cars that are made, 1 will be stolen.",
            "Jimmy Carter was the first U.S. President to be born in a hospital.",
            "Lightning strikes the earth about 8 million times a day.",
            "Humans use a total of 72 different muscles in speech.",
            "If you feed a seagull Alka-Seltzer, its stomach will explode.",
            "Only female mosquitoes bite.",
            "The U.S. Post Office handles 43 percent of the world’s mail.",
            "Most household dust is made of dead skin cells.",
            "One in eight million people has progeria, a disease that causes people to grow faster than they age.",
            "The male seahorse carries the eggs until they hatch instead of the female.",
            "Negative emotions such as anxiety and depression can weaken your immune system.",
            "Stephen Hawking was born exactly 300 years after Galileo died.",
            "Mercury is the only planet whose orbit is coplanar with its equator. ",
            "Venus and Uranus are the only planets that rotate opposite to the direction of their orbit.",
            "John Adams, Thomas Jefferson, and James Monroe died on July 4th.",
            "Baby Ruth candy bar was named after Grover Cleveland’s daughter, Ruth, not the baseball player.",
            "Dolphins can look in different directions with each eye. They can sleep with one eye open.",
            "The Falkland Isles (pop. about 2000) has over 700000 sheep (350 per person).",
            "There are 41,806 different spoken languages in the world today.",
            "The city of Venice stands on about 120 small islands.",
            "The past-tense of the English word “dare” is “durst”",
            "Beetles taste like apples, wasps like pine nuts, and worms\\xa0like fried bacon.",
            "Of all the words in the English language, the word 'set' has the most definitions!",
            "What is called a \"French kiss\" in the English speaking world is known as an \"English kiss\" in France.",
            "\"Almost\" is the longest word in the English language with all the letters in alphabetical order.",
            "\"Rhythm\" is the longest English word without a vowel.",
            "In 1386, a pig in France was executed by public hanging for the murder of a child",
            "A cockroach can live several weeks with its head cut off!",
            "Human thigh bones are stronger than concrete.",
            "You can't kill yourself by holding your breath",
            "There is a city called Rome on every continent.",
            "Your heart beats over 100,000 times a day!",
            "The skeleton of Jeremy Bentham is present at all important meetings of the University of London",
            "Right handed people live, on average, nine years longer than left-handed people",
            "Your ribs move about 5 million times a year, every time you breathe!",
            "One quarter of the bones in your body, are in your feet!",
            "Like fingerprints, everyone's tongue print is different!",
            "Fingernails grow nearly 4 times faster than toenails!",
            "Most dust particles in your house are made from dead skin!",
            "Present population of 5 billion plus people of the world is predicted to become 15 billion by 2080.",
            "Women blink nearly twice as much as men.",
            "Adolf Hitler was a vegetarian, and had only ONE testicle.",
            "Honey is the only food that does not spoil. ",
            "Months that begin on a Sunday will always have a \"Friday the 13th.\"",
            "Coca-Cola would be green if coloring weren’t added to it.",
            "On average a hedgehog's\\xa0heart beats 300 times a minute.",
            "More people are killed each year from bees than from snakes.",
            "The average lead pencil will draw a line 35 miles long or write approximately 50,000 English words.",
            "More people are allergic to cow's milk than any other food.",
            "Camels have three eyelids to protect themselves from blowing sand.",
            "The placement of a donkey's eyes in it’s' heads enables it to see all four feet at all times!",
            "The six official languages of the U.N. are: English, French, Arabic, Chinese, Russian and Spanish.",
            "Earth is the only planet not named after a god.",
            "It's against the law to burp, or sneeze in a church in Nebraska, USA.",
            "You're born with 300 bones, but by the time you become an adult, you only have 206.",
            "Some worms will eat themselves if they can't find any food!",
            "The world’s oldest piece of chewing gum is 9000 years old!",
            "The longest recorded flight\\xa0 of a chicken is 13 seconds",
            "Owls are the only birds that can see the color blue.",
            "A man named Charles Osborne had the hiccups for 69 years!",
            "A giraffe can clean its ears with its 21-inch tongue!",
            "The average person laughs 10 times a day!",
            "The Bible, the world's best-selling book, is also the world's most shoplifted book.",
            "Someone paid $14,000 for the bra worn by Marilyn Monroe in the film 'Some Like It Hot'.",
            "Your tongue is the only muscle in your body that is attached at only one end.",
            "More than 1,000 different languages are spoken on the continent of Africa.",
            "Buckingham Palace in England has over six hundred rooms.",
            "There was once an undersea post office in the Bahamas.",
            "Ninety percent of New York City cabbies are recently arrived immigrants.",
            "It's possible to lead a cow upstairs...but not downstairs.",
            "A snail can sleep for three years.\\xa0",
            "No word in the English language rhymes with \"MONTH\".",
            "Average life span of a major league baseball: 7 pitches.",
            "Our eyes are always the same size from birth, but our nose and ears never stop growing.",
            "\"Go.\" is the shortest complete sentence in the English language.",
            "The \"pound\" key on your keyboard (#) is called an octotroph.\\xa0",
            "The only domestic animal not mentioned in the Bible is the cat.\\xa0",
            "Table tennis balls have been known to travel off the paddle at speeds up to 160 km/hr.\\xa0",
            "Pepsi originally contained pepsin, thus the name.\\xa0",
            "The original story from \"Tales of 1001 Arabian Nights\" begins, \"Aladdin was a little Chinese boy.\"\\xa0",
            "Nutmeg is extremely poisonous if injected intravenously.\\xa0",
            "Honey is the only natural food that is made without destroying any kind of life. ",
            "The volume of the earth's moon is the same as the volume of the Pacific Ocean.\\xa0",
            "Cephalacaudal recapitulation is the reason our extremities develop faster than the rest of us.\\xa0",
            "Chinese Crested dogs can get acne.\\xa0",
            "Each year there is one ton of cement poured for each man woman and child in the world.\\xa0",
            "The house fly hums in the middle octave key of F.\\xa0",
            "The only capital letter in the Roman alphabet with exactly one end point is P.\\xa0",
            "The giant red star Betelgeuse has a diameter larger than that of the Earth's orbit around the sun.\\xa0",
            "Hummingbirds are the only animals that can fly backwards.\\xa0",
            "A cat's jaw cannot move sideways.",
            "The human heart creates enough pressure when it pumps out to the body to squirt blood 30 feet.",
            "The flea can jump 350 times its body length. It's like a human jumping the length of a football field.",
            "Some lions mate over 50 times a day.",
            "Rubber bands last longer when refrigerated.\\xa0",
            "The average person's left hand does 56% of the typing.\\xa0",
            "The longest one-syllable word in the English language is \"screeched.\"\\xa0",
            "All of the clocks in the movie \"Pulp Fiction\" are stuck on 4:20.\\xa0",
            "\"Dreamt\" is the only English word that ends in the letters \"mt.\"\\xa0",
            "Maine is the only state (in USA) whose name is just one syllable.\\xa0",
            "The giant squid has the largest eyes in the world.\\xa0",
            "In England, the Speaker of the House is not allowed to speak.\\xa0",
            "Mr. Rogers was an ordained minister.\\xa0",
            "A rat can last longer without water than a camel.",
            "Your stomach has to produce a new layer of mucus every two weeks or it will digest itself.",
            "A female ferret will die if it goes into heat and cannot find a mate.",
            "A 2\" X 4\" is really 1-1/2\" by 3-1/2\".",
            "On average, 12 newborns will be given to the wrong parents daily.",
            "There are no words in the dictionary that rhyme with orange, purple, silver and month.",
            "If one places a tiny amount of liquor on a scorpion, it will instantly go mad and sting itself to death. ",
            "The first CD pressed in the US was Bruce Springsteen\\'s \"Born in the USA.\"",
            "Sherlock Holmes NEVER said, \"Elementary, my dear Watson.\"",
            "California consumes more bottled water than any other product. ",
            "California has issued 6 drivers licenses to people named \"Jesus Christ.\"",
            "In 1980, a Las Vegas hospital suspended workers for betting on when patients would die. ",
            "Nevada is the driest state in the U.S.. Each year it averages 7.5 inches (19 cm) of rain. ",
            "In Utah, it is illegal to swear in front of a dead person. ",
            "Salt Lake City, Utah has a law against carrying an unwrapped ukulele on the street. ",
            "Arizona was the last of the 48 adjoining continental states to enter the Union.",
            "It is illegal to hunt camels in the state of Arizona. ",
            "Wyoming was the first state to give women the right to vote in 1869. ",
            "Denver, Colorado lays claim to the invention of the cheeseburger. ",
            "The first license plate on a car in the United States was issued in Denver, Colorado in 1908. ",
            "The state of Maryland has no natural Lakes. ",
            "Illinois has the highest number of personalized license plates than any other state. ",
            "Residents of Houston, Texas lead the U.S. in eating out - approximately 4.6 times per week. ",
            "Laredo, Texas is the U.S.'s farthest inland port. ",
            "Rugby, North Dakota is the geographical center of North America. ",
            "Butte County, South Dakota is the geographical center of the U.S. ",
            "Louisiana's capital building is the tallest one of any U.S. state.",
            "Hawaii is the only coffee producing state. ",
            "One in seven workers in Boston, Massachusetts walks to work. ",
            "The \"Dull Men\\'s Hall of Fame\" is located in Carroll, Wisconsin. ",
            "Gary, Indiana is the murder capital of the U.S. - probably the world. ",
            "Alabama was the first state to recognize Christmas as an official holiday.",
            "The largest NFL stadium is the Pontiac Silverdome in Detroit, Michigan.",
            "Michigan was the first state to have roadside picnic tables. ",
            "No matter where you stand in Michigan, you are never more than 85 miles from a Great Lake. ",
            "The official beverage of Ohio is tomato juice. ",
            "Georgia\\'s state motto is \"Wisdom, Justice and Moderation.\" ",
            "The U.S. city with the highest rate of lightning strikes per capita is Clearwater, Florida. ",
            "It's illegal to spit on the sidewalk in Norfolk, Virginia. ",
            "The first streetlights in America were installed in Philadelphia around 1757. ",
            "The highest point in Pennsylvania is lower than the lowest point in Colorado. ",
            "If you were to take a taxicab from New York City to Los Angeles, it would cost you $8,325. ",
            "The NY phone book had 22 Hitlers before WWII. The NY phone book had 0 Hitlers after WWII. ",
            "In New York State, it is illegal to but any alcohol on Sundays before noon.",
            "There were 240 pedestrian fatalities in New York City in 1994. ",
            "Columbia University is the second largest landowner in New York City, after the Catholic Church. ",
            "Montpelier, Vermont is the only state capital without a McDonalds.",
            "Maine is the only state that has borders with only one other state. ",
            "The first McDonald's restaurant in Canada was in Richmond, British Columbia.",
            "In 1984, a Canadian farmer began renting advertising space on his cows.",
            "There are more donut shops in Canada per capita than any other country. ",
            "0.3% of all road accidents in Canada involve a Moose. ",
            "In the great fire of London in 1666 half of London was burnt down but only 6 people were injured. ",
            "In Quebec, there is an old law that states margarine must be a different color than butter. ",
            "The largest taxi fleet in the world is found in Mexico City. The city boasts a fleet of over 60,000 taxis. ",
            "More than 90% of the Nicaraguan people are Roman Catholic. ",
            "Cuba is the only island in the Caribbean to have a railroad. ",
            "Jamaica has the most churches per square mile than any other country in the world. ",
            "The angel falls in Venezuela are nearly 20 times taller than Niagara Falls.",
            "Canada is the only country not to win a gold medal in the summer Olympic games while hosting. ",
            "The Amazon is the world's largest river, 3,890 miles (6,259 km) long. ",
            "The town of Calma, Chile in the Atacama Desert has never had rain. ",
            "The people of France eat more cheese than any other country in the world.",
            "King Louis XIX ruled France for 15 minutes. ",
            "The most common name in Italy is Mario Rossi. ",
            "Greece's national anthem has 158 verses. ",
            "In ancient Greece \"idiot\" meant a private citizen or layman. ",
            "Bulgarians are known to be the biggest yogurt eaters in the world.",
            "Czechs are the biggest consumers of beer per male in the world. ",
            "A Czech man, Jan Honza Zampa, holds the record for drinking one liter of beer in 4.11 seconds. ",
            "Netherlands is the only country with a national dog. ",
            "When we think of Big Ben in London, we think of the clock. Actually, it's the bell. ",
            "The Automated Teller Machine (ATM) was introduced in England in 1965. ",
            "Buckingham Palace has 602 rooms. ",
            "Icelanders consume more Coca-Cola per Capita than any other nation.",
            "Until 1997, there were more pigs than people in Denmark. ",
            "There is a hotel in Sweden built entirely out of ice; it is rebuilt every year. ",
            "Sweden has the least number of murders annually. ",
            "Lithuania has the highest suicide rate in the world. ",
            "The country code for Russia is \"007\". ",
            "Russians generally answer the phone by saying, \"I\\'m listening\". ",
            "The U.S. bought Alaska for 2 cents an acre from Russia. ",
            "1 in 5 of the world's doctors are Russian. ",
            "Antarctica is the only continent that does not have land areas below sea level. ",
            "The people of Israel consume more turkeys per capita than any other country.",
            "Nepal is the only country that has a non-rectangular flag. It is also asymmetrical. ",
            "1,800 cigarettes are smoked per person each year in China. ",
            "Respiratory Disease is China's leading cause of death. ",
            "There are more than 40,000 characters in the Chinese script. ",
            "More people speak English in China than the United States. ",
            "The toothbrush was invented in China in 1498. ",
            "Mongolia is the largest landlocked country. ",
            "Vatican City is the smallest country in the world, with a population of 1000 and just 108.7 acres. ",
            "In Japan, watermelons are squared. It's easier to stack them that way.",
            "98% of Japanese are cremated. ",
            "The number \"four\" is considered unlucky in Japan because it is pronounced the same as \"death\". ",
            "The average Japanese household watches more than 10 hours of television a day. ",
            "The Philippines has about 7,100 islands, of which only about 460 are more than 1 square mile in area.",
            "Yo-yos were used as weapons by warriors in the Philippines in the 16th century.",
            "Australian soldiers used the song \"We\\'re Off to See the Wizard\" as a marching song in WWII. ",
            "The Australian $5 to $100 notes are made of plastic. ",
            "The Nullarbor Plain of Australia covers 100,000 square miles (160,900 km) without a tree. ",
            "Tasmania, Australia has the cleanest air in the inhabited world. ",
            "Greenland is the largest island in the world. ",
            "The first female guest host of \"Saturday Night Live\" was Candace Bergen.",
            "In 1933, Mickey Mouse, an animated cartoon character, received 800,000 fan letters. ",
            "The Simpsons is the longest running animated series on TV. ",
            "The first toilet ever seen on television was on \"Leave It to Beaver.\" ",
            "In every episode of Seinfeld there is a Superman somewhere. ",
            "The average human brain has about 100 billion nerve cells. ",
            "Nerve impulses to and from the brain travel as fast as 170 miles (274 km) per hour. ",
            "The thyroid cartilage is more commonly known as the adams apple. ",
            "Your stomach needs to produce a new layer of mucus every two weeks or it would digest itself. ",
            "The average life of a taste bud is 10 days. ",
            "The average cough comes out of your mouth at 60 miles (96.5 km) per hour.",
            "Relative to size, the strongest muscle in the body is the tongue. ",
            "When you sneeze, all your bodily functions stop even your heart. ",
            "Babies are born without knee caps. They don't appear until the child reaches 2-6 years of age. ",
            "Right handed people live, on average, nine years longer than left handed people do. ",
            "Children grow faster in the springtime. ",
            "It takes the stomach an hour to break down cows’ milk. ",
            "Women blink nearly twice as much as men. ",
            "Blondes have more hair than dark-haired people do. ",
            "There are 10 human body parts that are only 3 letters long (eye hip arm leg ear toe jaw rib lip gum). ",
            "If you go blind in one eye you only lose about one fifth of your vision but all your sense of depth. ",
            "The average human head weighs about 8 pounds. ",
            "In the average lifetime, a person will walk the equivalent of 5 times around the equator. ",
            "An average human scalp has 100,000 hairs. ",
            "The average human blinks their eyes 6,205,000 times each year. ",
            "Your skull is made up of 29 different bones. ",
            "Ancient Egyptians shaved off their eyebrows to mourn the deaths of their cats.",
            "Hair is made from the same substance as fingernails. ",
            "The surface of the human skin is 6.5 square feet (2m). ",
            "15 million blood cells are destroyed in the human body every second. ",
            "The pancreas produces Insulin. ",
            "The most sensitive cluster of nerves is at the base of the spine. ",
            "The human body is comprised of 80% water. ",
            "The average human will shed 40 pounds of skin in a lifetime. ",
            "Human thighbones are stronger than concrete. ",
            "There are 45 miles of nerves in the skin of a human being. ",
            "Canadian researchers have found that Einstein's brain was 15% wider than normal. ",
            "While in Alcatraz, Al Capone was inmate #85. ",
            "Astronaut Neil Armstrong first stepped on the moon with his left foot.",
            "Jim Morrison, of the 60's rock group The Doors, was the first rock star to be arrested on stage. ",
            "Frank Lloyd Wright's son invented Lincoln Logs. ",
            "Peter Falk, who played \"Columbo,\" has a glass eye. ",
            "Barbie\\'s full name is \"Babara Millicent Roberts.\" ",
            "The mother of Michael Nesmith of \"The Monkees\" invented whiteout. ",
            "Isaac Asimov is the only author to have a book in every Dewey-decimal category. ",
            "Shakespeare invented the word \"assassination\" and \"bump.\" ",
            "Leonardo Da Vinci invented the scissors. ",
            "Adolf Hitler's mother seriously considered having an abortion but was talked out of it by her doctor. ",
            "Marilyn Monroe had six toes. ",
            "The shortest British monarch was Charles I, who was 4 feet 9 inches. ",
            "Tina Turner's real name is Annie Mae Bullock. ",
            "Beethoven dipped his head in cold water before he composed. ",
            "President John F Kennedy could read 4 newspapers in 20 minutes. ",
            "Bob Dylan's real name is Robert Zimmerman. ",
            "Sigmund Freud had a morbid fear of ferns. ",
            "Anne Boleyn, Queen Elizabeth I's mother, had six fingers on one hand. ",
            "Orville Wright was involved in the first aircraft accident. His passenger, a Frenchman, was killed. ",
            "The sound of E.T. walking was made by someone squishing her hands in jelly.",
            "Cher\\'s last name was \"Sarkissian.\" She changed it because no one could pronounce it. ",
            "Sugar was first added to chewing gum in 1869 by a dentist, William Semple.",
            "Paper was invented early in the second century by Chinese eunuch. ",
            "Sir Isaac Newton was only 23 years old when he discovered the law of universal gravitation. ",
            "Hannibal had only one eye after getting a disease while attacking Rome.",
            "A blue whales heart only beats nine times per minute. ",
            "A cat uses its whiskers to determine if a space is too small to squeeze through. ",
            "A chameleon's tongue is twice the length of its body. ",
            "A crocodiles tongue is attached to the roof of its mouth. ",
            "Rodent's teeth never stop growing. ",
            "A shark can detect one part of blood in 100 million parts of water. ",
            "The penguin is the only bird that can swim but can't fly. ",
            "The cheetah is the only cat that can't retract its claws. ",
            "A lion's roar can be heard from five miles away. ",
            "Emus and kangaroos can't walk backwards. ",
            "Cats have over 100 vocal sounds; dogs only have 10. ",
            "A mole can dig a tunnel 300 feet (91 m) long in just one night. ",
            "Insects outnumber humans 100,000,000 to one. ",
            "Sharkskin has tiny tooth-like scales all over. ",
            "Chameleons can move their eyes in two directions at the same time.",
            "Koalas never drink water. They get fluids from the eucalyptus leaves they eat.",
            "A cow gives nearly 200,000 glasses of milk in her lifetime. ",
            "When sharks take a bite, their eyes roll back and their teeth jut out. ",
            "Camels chew in a figure 8 pattern. ",
            "Proportional to their size, cats have the largest eyes of all mammals.",
            "Sailfish can leap out of the water and into the air at a speed of 50 miles (81 km) per hour. ",
            "The catfish has the most taste buds of all animals, having over 27,000 of them. ",
            "A skunk's smell can be detected by a human a mile away. ",
            "A lion in the wild usually makes no more than 20 kills a year. ",
            "In space, astronauts cannot cry, because there is no gravity, so the tears can't flow.",
            "The state of Florida is bigger than England.",
            "One in every 4 Americans has appeared on television.",
            "The average American/Canadian will eat about 11.9 pounds of cereal per year! ",
            "There are over 58 million dogs in the US",
            "Dogs and cats consume over $11 billion worth of pet food a year",
            "Baby robins eat 14 feet of earthworms every day",
            "In Raiders of the Lost Ark there is a wall carving of R2-D2 and C-3P0 behind the ark",
            "\"I\" is the most spoken word in the English language ",
            "\"You\" is the second most spoken English word ",
            "Spain leads the world in cork production",
            "There are 1,792 steps in the Eiffel Tower",
            "There is a city in Norway called \"Hell\"",
            "The human brain uses the same amount of energy as a 10-watt light bulb",
            "The human feet perspire half a pint of fluid a day",
            "An Olympic gold medal must contain 92.5 percent silver",
            "There are 240 dots on an arcade Pac-Man game",
            "The San Francisco Cable cars are the only mobile National Monuments",
            "Lee Harvey Oswald's cadaver tag sold at an auction for $6,600 in 1992. ",
            "A pound of houseflies contains more protein than a pound of beef ",
            "The average American works 24,000 hours in their lifetime just to pay their taxes ",
            "The U.S. military operates 234 golf courses",
            "40% of all people who come to a party in your home snoop in your medicine cabinet ",
            "A duck's quack doesn't echo, and no one knows why.",
            "Non-dairy creamer is flammable.",
            "Pinocchio is Italian for \"pine head.\"",
            "There are more than 10 million bricks in the Empire State Building.",
            "The sun is 330,330 times larger than the earth.",
            "Most American car horns honk in the key of F.",
            "The name Wendy was made up for the book \"Peter Pan.\"",
            "Barbie's full name is Barbara Millicent Roberts.",
            "Every time you lick a stamp, you consume 1/10 of a calorie.",
            "The average person falls asleep in seven minutes.",
            "Studies show that if a cat falls off the seventh floor of a building it has about thirty percent less chance of surviving than a cat that falls off the twentieth floor. It supposedly takes about eight floors for the cat to realize what is occurring, relax and correct itself.",
            "Your stomach has to produce a new layer of mucus every 2 weeks otherwise it will digest itself.",
            "The citrus soda 7-UP was created in 1929; '7' was selected after the original 7-ounce containers and 'UP' for the direction of the bubbles.",
            "101 Dalmatians, Peter Pan, Lady and the Tramp, and Mulan are the only Disney cartoons where both parents are present and don't die throughout the movie.  .",
            "A pig's orgasm lasts for 30 minutes.",
            "'Stewardesses' is the longest word that is typed with only the left hand.",
            "To escape the grip of a crocodile's jaws, push your thumbs into its eyeballs - it will let you go instantly.",
            "Reindeer like to eat bananas.",
            "No word in the English language rhymes with month, orange, silver and purple.",
            "The word \"samba\" means \"to rub navels together.\"",
            "Mel Blanc (the voice of Bugs Bunny) was allergic to carrots.",
            "The electric chair was invented by a dentist.",
            "The very first bomb dropped by the Allies on Berlin during World War II Killed the only elephant in the Berlin Zoo.",
            "More people are killed annually by donkeys than airplane crashes.",
            "A 'jiffy' is a unit of time for 1/100th of a second.",
            "A whale's penis is called a dork.",
            "Because of the rotation of the earth, an object can be thrown farther if it is thrown west.",
            "The average person spends 6 months of their life sitting at red lights.",
            "In 1912 a law passed in Nebraska where drivers in the country at night were required to stop every 150 yards, send up a skyrocket, wait eight minutes for the road to clear before proceeding cautiously, all the while blowing their horn and shooting off flares.",
            "More Monopoly money is printed in a year, than real money throughout the world.",
            "Caesar salad has nothing to do with any of the Caesars. It was first concocted in a bar in Tijuana, Mexico, in the 1920's.",
            "One quarter of the bones in your body are in your feet.",
            "Crocodiles and alligators are surprisingly fast on land.  Although they are rapid, they are not agile.  So, if being chased by one, run in a zigzag line to lose him or her.",
            "Seattle’s Fremont Bridge rises up and down more than any drawbridge in the world.",
            "Right-handed people live, on average; nine years longer than left handed people.",
            "Ten percent of the Russian government's income comes from the sale of vodka.",
            "In the United States, a pound of potato chips costs two hundred times more than a pound of potatoes.  ",
            "A giraffe can go without water longer than a camel.",
            "A person cannot taste food unless it is mixed with saliva. For example, if a strong-tasting substance like salt is placed on a dry tongue, the taste buds will not be able to taste it. As soon as a drop of saliva is added and the salt is dissolved, however, a definite taste sensation results. This is true for all foods.",
            "Nearly 80% of all animals on earth have six legs.",
            "In the marriage ceremony of the ancient Inca Indians of Peru, the couple was considered officially wed when they took off their sandals and handed them to each other.",
            "Ninety percent of all species that have become extinct have been birds.",
            "There is approximately one chicken for every human being in the world.",
            "Most collect calls are made on father's day.",
            "The first automobile race ever seen in the United States was held in Chicago in 1895. The track ran from Chicago to Evanston, Illinois. The winner was J. Frank Duryea, whose average speed was 71/2 miles per hour.",
            "Each of us generates about 3.5 pounds of rubbish a day, most of it paper.",
            "Women manage the money and pay the bills in  75% of all Americans households.",
            "A rainbow can be seen only in the morning or late afternoon. It can occur only when the sun is 40 degrees or less above the horizon.",
            "It has NEVER rained in Calama, a town in the Atacama Desert of Chile.",
            "It costs more to buy a new car today in the United States than it cost Christopher Columbus to equip and undertake three voyages to and from the New World.",
            "The plastic things on the end of shoelaces are called aglets.",
            "An eighteenth-century German named Matthew Birchinger, known as \"the little man of Nuremberg,\" played four musical instruments including the bagpipes, was an expert calligrapher, and was the most famous stage magician of his day. He performed tricks with the cup and balls that have never been explained. Yet Birchinger had no hands, legs, or thighs, and was less than 29 inches tall.",
            "Daylight Saving Time is not observed in most of the state of Arizona and parts of Indiana.",
            "Ants closely resemble human manners:  When they wake, they stretch & appear to yawn in a human manner before taking up the tasks of the day.",
            "Bees have 5 eyes. There are 3 small eyes on the top of a bee's head and 2 larger ones in front.",
            "Count the number of cricket chirps in a 15-second period, add 37 to the total, and your result will be very close to the actual outdoor Fahrenheit temperature.",
            "One-fourth of the world's population lives on less than $200 a year.  Ninety million people survive on less than $75 a year.",
            "Butterflies taste with their hind feet.",
            "Only female mosquito’s' bite and most are attracted to the color blue twice as much as to any other color.",
            "If one places a tiny amount of liquor on a scorpion, it will instantly go mad and sting itself to death.",
            "It is illegal to hunt camels in the state of Arizona.",
            "In eighteenth-century English gambling dens, there was an employee whose only job was to swallow the dice if there was a police raid.",
            "There are no clocks in Las Vegas gambling casinos.",
            "The human tongue tastes bitter things with the taste buds toward the back. Salty and pungent flavors are tasted in the middle of the tongue, sweet flavors at the tip!",
            "The first product to have a bar code was Wrigley’s gum. ",
            "When you sneeze, air and particles travel through the nostrils at speeds over100 mph.  During this time, all bodily functions stop, including your heart, contributing to the impossibility of keeping one's eyes open during a sneeze.",
            "Annual growth of WWW traffic is 314",
            "%60 of all people using the Internet, use it for pornography.",
            "In 1778, fashionable women of Paris never went out in blustery weather without a lightning rod attached to their hats.",
            "Sex burns 360 calories per hour. ",
            "A raisin dropped in a glass of fresh champagne will bounce up and down continually from the bottom of the glass to the top.",
            "Celery has negative calories! It takes more calories to eat a piece of celery than the celery has in it.",
            "The average lead pencil will draw a line 35 miles long or write approximately 50",
            "English words.  More than 2 billion pencils are manufactured each year in the United States. If these were laid end to end they would circle the world nine times.",
            "The pop you hear when you crack your knuckles is actually a bubble of gas burning.",
            "A literal translation of a standard traffic sign in China: \"Give large space to the festive dog that makes sport in the roadway.\"",
            "You burn more calories sleeping than you do watching TV.",
            "Larry Lewis ran the 100-yard dash in 17.8 seconds in 1969, thereby setting a new world's record for runners in the 100-years-or-older class. He was 101.",
            "In a lifetime the average human produces enough quarts of spit to fill 2 swimming pools.",
            "It's against the law to doze off under a hair dryer in Florida/against the law to slap an old friend on the back in Georgia/against the law to Play hopscotch on a Sunday in Missouri.",
            "Barbie's measurements, if she were life-size, would be 39-29-33.",
            "The human heart creates enough pressure to squirt blood 30ft.",
            "One third of all cancers are sun related.",
            "THE MOST UNUSUAL CANNONBALL: On two occasions, Miss 'Rita Thunderbird' remained inside the cannon despite a lot of gunpowder encouragement to do otherwise. She performed in a gold lamé bikini and on one of the two occasions (1977) Miss Thunderbird remained lodged in the cannon, while her bra was shot across the Thames River.",
            "It has been estimated that humans use only 10% of their brain.",
            "Valentine Tapley from Pike County, Missouri  grew chin whiskers attaining a length of twelve feet six inches from 1860 until his death 1910, protesting Abraham Lincoln's election to the presidency.",
            "Most Egyptians died by the time they were 30 about 300 years ago,",
            "For some time Frederic Chopin, the composer and pianist, wore a beard on only one side of his face, explaining: \"It does not matter, my audience sees only my right side.\"",
            "1 in every 4 Americans has appeared someway or another on television.",
            "1 in 8 Americans has worked at a McDonalds restaurant.",
            "70% of all boats sold are used for fishing.",
            "Studies have shown that children laugh an average of 300 times/day and adults 17 times/day, making the average child more optimistic, curious, and creative than the adult.",
            "A pregnant goldfish is called a twit.",
            "The shortest war in history was between Zanzibar and England in 1896. Zanzibar surrendered after 38 minutes. ",
            "You were born with 300 bones, but by the time you are an adult you will only have 206.",
            "If you go blind in one eye you only lose about one fifth of your vision but all your sense of depth.",
            "Women blink nearly twice as much as men.",
            "The strongest muscle (Relative to size) in the body is the tongue.",
            "A Boeing 747's wingspan is longer than the Wright brother's first flight.",
            "American Airlines saved $40 in 1987 by eliminating one olive from each salad served in first-class. ",
            "Average life span of a major league baseball: 7 pitches.",
            "A palindrome is a sentence or group of sentences that reads the same backwards as it does forward: Ex:  'Red rum, sir, is murder.' 'Ma is as selfless as I am.' 'Nurse, I spy gypsies. Run!'  'A man, a plan, a canal - Panama.' 'He lived as a devil, eh?'",
            "The first CD pressed in the US was Bruce Springsteen's 'Born in the USA'",
            "In 1986 Congress & President Ronald Reagan signed Public Law 99-359, which changed Daylight Saving Time from the last Sunday in April to the first Sunday in April.  It was estimated to save the nation about 300,000 barrels of oil each year by adding most of the month April to D.S.T.",
            "The thumbnail grows the slowest, the middle nail the fastest, nearly 4 times faster than toenails.",
            "The Human eyes never grow, but nose and ears never stop growing.",
            "The 57 on Heinz ketchup bottles represents the number of varieties of pickles the company once had. ",
            "Tom Sawyer was the first novel written on a typewriter.",
            "If Texas were a country, its GNP would be the fifth largest of any country in the world.",
            "There are 1 million ants for every human in the world.",
            "Odds of being killed by lightening? 1 in 2million/killed in a car crash? 1 in 5,000/killed by falling out of bed? 1 in 2million/killed in a plane crash? 1 in 25 million.",
            "Since 1978, 37 people have died by Vending Machine's falling on them.  13 people are killed annually.  All this while trying to shake merchandise out of them. 113 people have been injured.",
            "Half the foods eaten throughout the world today were developed by farmers in the Andes Mountains (including potatoes, maize, sweet potatoes, squash, all varieties of beans, peanuts, manioc, papayas, strawberries, mulberries and many others).",
            "The 'Golden Arches' of fast food chain McDonalds is more recognized worldwide than the religious cross of Christianity.",
            "Former basketball superstar Michael Jordan is the most recognized face in the world, more than the pope himself.",
            "The average talker sprays about 300 microscopic saliva droplets per minute, about 2.5 droplets per word.",
            "The Earth experiences 50,000 Earth quakes per year and is hit by Lightning 100 times a second.",
            "Every year 11,000 Americans injure themselves while trying out bizarre sexual positions.",
            "If we had the same mortality rate now as in 1900, more than half the people in the world today would not be alive.",
            "On average, Americans eat 18 acres of pizza everyday.",
            "Researchers at the Texas Department of Highways in Fort Worth determined the cow population of the U.S. burps some 50 million tons of valuable hydrocarbons into the atmosphere each year.  The accumulated burps of ten average cows could keep a small house adequately heated and its stove operating for a year.",
            "During a severe windstorm or rainstorm the Empire State Building sways several feet to either side.",
            "In the last 3,500 years, there have been approximately 230 years of peace throughout the civilized world.",
            "The Black Death reduced the population of Europe by one third in the period from 1347 to 1351.",
            "The average person spends about two years on the phone in a lifetime.",
            "Length of beard an average man would grow if he never shaved 27.5 feet",
            "Over 60% of all those who marry get divorced.",
            "400-quarter pounders can be made from 1 cow.",
            "A full-loaded supertanker traveling at normal speed takes at least 20 minutes to stop.",
            "Coca-Cola was originally green.",
            "Men can read smaller print than women; women can hear better.",
            "Hong Kong holds the most Rolls Royce’s per capita.",
            "Average number of days a West German goes without washing his underwear: 7",
            "WWII fighter pilots in the South Pacific armed their airplanes while stationed with .50 caliber machine gun ammo belts measuring 27 feet before being loaded into the fuselage. If the pilots fired all their ammo at a target, he went through \"the whole 9 yards\", hence the term.",
            "Average number of people airborne over the US any given hour: 61,000.",
            "Intelligent people have more zinc and copper in their hair.",
            "Iceland consumes more Coca-Cola per capita than any other nation.",
            "In the early 1940s, the FCC assigned television's Channel 1 to mobile services (like two-way radios in taxis) but did not re-number the other channel assignments.",
            "The San Francisco Cable cars are the only mobile National Monuments.",
            "Firehouses have circular stairways originating from the old days when the engines were pulled by horses. The horses were stabled on the ground floor and figured out how to walk up straight staircases.",
            "Statues in parks: If the horse has both front legs in the air, the person died in battle; if the horse has one front leg in the air, the person died as a result of wounds received in battle; if the horse has all four legs on the ground, the person died of natural causes.",
            "The expression 'to get fired' comes from long ago Clans that wanted to get rid of unwanted people, so they would burn their houses instead of killing them, creating the term 'Got fired'.",
            "\"I am.\" is the shortest complete sentence in the English language.",
            "Hershey's Kisses are called that because the machine that makes them looks like it's kissing the conveyor belt.",
            "The phrase \"rule of thumb\" is derived from an old English law, which stated that you couldn\\'t beat your wife with anything wider than your thumb.",
            "The longest recorded flight of a chicken is thirteen seconds.",
            "The Eisenhower interstate system requires that one mile in every five must be straight in case of war or emergency, they could be used as airstrips.",
            "The name Jeep came from the abbreviation used in the army. G.P. for 'General Purpose' vehicle.",
            "The Pentagon, in Arlington, Virginia, has twice as many bathrooms as is necessary, because when it was built in the 1940s, the state of Virginia still had segregation laws requiring separate toilet facilities for blacks and whites.",
            "The cruise liner, Queen Elizabeth II, moves only six inches for each gallon of diesel that it burns.",
            "If you have three quarters, four dimes, and four pennies, you have $1.19, the largest amount of money in coins without being able to make change for a dollar.",
            "In Aspen Colorado, you can have a maximum income of $104,000 and still receive government subsidized housing.",
            "Honking of car horns for a couple that just got married is an old superstition to insure great sex.",
            "Dr. Kellogg introduced Kellogg's Corn Flakes in hopes that it would reduce masturbation. ",
            "The sperm of a mouse is actually longer than the sperm of an elephant.",
            "In medieval France, unfaithful wives were made to chase a chicken through town naked.",
            "The Black Widow spider eats her mate during or after sex.",
            "Napoleon's penis was sold to an American Urologist for $40,000. ",
            "Eating the heart of a male Partridge was the cure for impotence in ancient Babylon.",
            "A bull can inseminate 300 cows from one single ejaculation.",
            "When a Hawaiian woman wears a flower over her left ear, it means that she is not available.",
            "The \"save\" icon on Microsoft Word shows a floppy disk with the shutter on backwards.",
            "The only nation whose name begins with an \"A\", but doesn\\'t end in an \"A\" is Afghanistan.",
            "The following sentence: \\'A rough-coated, dough-faced, thoughtful ploughman strode through the streets of Scarborough; after falling into a slough, he coughed and hiccoughed.\\' Contains the nine different pronunciations of \"ough\" in the English Language.",
            "The verb \"cleave\" is the only English word with two synonyms which are antonyms of each other: adhere and separate.",
            "The only 15-letter word that can be spelled without repeating a letter is uncopyrightable. ",
            "The shape of plant collenchyma’s cells and the shape of the bubbles in beer foam are the same - they are orthotetrachidecahedrons.",
            "Emus and kangaroos cannot walk backwards, and are on the Australian coat of arms for that reason.",
            "Cats have over one hundred vocal sounds, while dogs only have about ten.",
            "Blueberry Jelly Bellies were created especially for Ronald Reagan. ",
            "PEZ candy even comes in a Coffee flavor.",
            "The first song played on Armed Forces Radio during operation Desert Shield was \"Rock the Casba\" by the Clash. ",
            "Non-dairy creamer is flammable. ",
            "The airplane Buddy Holly died in was the \"American Pie.\" (Thus the name of the Don McLean song.)",
            "Each king in a deck of playing cards represents a great king from history. Spades - King David, Clubs - Alexander the Great, Hearts - Charlemagne, and Diamonds - Julius Caesar.",
            "Golf courses cover 4% of North America.",
            "The average person will accidentally eat just under a pound of insects every year.",
            "Until 1994, world maps and globes sold in Albania only had Albania on them.",
            "The value of Pi will be officially \"rounded down\" to 3.14 from 3.14159265359 on December 31, 1999.",
            "The Great Wall of China is the only man-made structure visible from space.",
            "A piece of paper can be folded no more then 9 times.",
            "The amount of computer Memory required to run WordPerfect for Win95 is 8 times the amount needed aboard the space shuttle.",
            "The average North American will eat 35,000 cookies during their life span.",
            "Between 25% and 33% of the population sneeze when exposed to light.",
            "The most common name in world is Mohammed.",
            "Mount Olympus Mons on Mars is three times the size of Mount Everest.",
            "Most toilets flush in E flat.",
            "2,000 pounds of space dust and other space debris fall on the Earth every day.",
            "Each month, there is at least one report of UFOs from each province of Canada.",
            "40,000 Americans are injured by toilets each year.",
            "You can be fined up to $1,000 for whistling on Sunday in Salt Lake City, Utah.",
            "It takes about 142.18 licks to reach the center of a Tootsie pop.",
            "The serial number of the first MAC ever produced was 2001.",
            "It is illegal to eat oranges while bathing in California.",
            "If done perfectly, a rubix cube combination can be solved in 17 turns.",
            "The average American butt is 14.9 inches long.",
            "More bullets were fired in 'Starship Troopers' than any other movie ever made.",
            "60% of electrocutions occur while talking on the telephone during a thunderstorm.",
            "The name of the girl on the statue of liberty is Mother of Exiles. ",
            "3.6 cans of Spam are consumed each second.",
            "There's a systematic lull in conversation every 7 minutes.",
            "The buzz from an electric razor in America plays in the key of B flat; Key of G in England.",
            "There are 1,575 steps from the ground floor to the top of the Empire State building. ",
            "The world's record for keeping a Lifesaver in the mouth with the hole intact is 7 hrs 10 min.",
            "There are 293 ways to make change for a dollar.",
            "The world record for spitting a watermelon seed is 65 feet 4 inches.",
            "In the Philippine jungle, the yo-yo was first used as a weapon.",
            "Dueling is legal in Paraguay as long as both parties are registered blood donors.",
            "Texas is also the only state that is allowed to fly its state flag at the same height as the U.S. flag.",
            "The three most recognized Western names in China are Jesus Christ, Richard Nixon, & Elvis Presley.",
            "There is a town in Newfoundland, Canada called Dildo. ",
            "The Boston University Bridge (on Commonwealth Avenue, Boston, Massachusetts) is the only place in the world where a boat can sail under a train driving under a car driving under an airplane.",
            "All 50 states are listed across the top of the Lincoln Memorial on the back of the $5 bill.",
            "In space, astronauts are unable to cry, because there is no gravity and the tears won't flow.",
            "Chewing gum while peeling onions will keep you from crying.",
            "There are more plastic flamingos in the U.S that there are real ones.",
            "The crack of a whip is actually a tiny sonic boom, since the tip breaks the sound barrier.",
            "Jupiter is bigger than all the other planets in our solar system combined.",
            "Hot water is heavier than cold.",
            "The common idea that only 10% of the brain is used it not true as it is impossible to determine the actual percentage because of the complexity of the brain.",
            "Lawn darts are illegal in Canada.",
            "There are more psychoanalysts per capita in Buenos Aires than any other place in the world.",
            "Between 2 and 3 jockeys are killed each year in horse racing.",
            "5,840 people with pillow related injuries checked into U.S. emergency rooms in 1992.",
            "The average woman consumes 6 lbs of lipstick in her lifetime.",
            "Some individuals express concern sharing their soap, rightly so, considering 75% of all people wash from top to bottom.",
            "Conception occurs most in the month of December.",
            "CBS\\' \"60 Minutes\" is the only TV show without a theme song/music.",
            "Half of all Americans live within 50 miles of their birthplace.",
            "'Obsession' is the most popular boat name.",
            "On average, Americans' favorite smell is banana.",
            "If one spells out numbers, they would have to count to One Thousand before coming across the letter \"A\".",
            "Honey is the only food which does not spoil.",
            "3.9% of all women do not wear underwear.",
            "This common everyday occurrence composed of 59% nitrogen, 21% hydrogen, and 9% dioxide is called a 'fart'.",
            "\"Evaluation and Parameterization of Stability and Safety Performance Characteristics of Two and Three Wheeled Vehicular Toys for Riding.\" Title of a $230, 000 research project proposed by the Department of Health, Education and Welfare, to study the various ways children fall off bicycles.",
            "Babies are born without kneecaps. They don't appear until the child reaches 2-6 years of age.",
            "Meteorologists claim they're right 85% of the time (think about that one!)",
            "In 1980, a Las Vegas hospital suspended workers for betting on when patients would die.",
            "Los Angeles' full name 'El Pueblo de Nuestra Senora la Reina de Los Angeles de Porciuncula' is reduced to 3.63% of its size in the abbreviation 'L.A.'.",
            "If you went out into space, you would explode before you suffocated because there's no air pressure.",
            "The only real person to ever to appear on a pez dispenser was Betsy Ross.",
            "Mike Nesmith's (the guitarist of The Monkeys) mom invented White Out. ",
            "Only 6 people in the whole world have died from moshing.",
            "241.     In a test performed by Canadian scientists, using various different styles of music, it was determined that chickens lay the most eggs when pop music was played.",
            "The storage capacity of human brain exceeds 4 Terabytes.",
            "In Vermont, the ratio of cows to people is 10: 1",
            "Any free-moving liquid in outer space will form itself into a sphere, because of its surface tension.",
            "The average American looks at eight houses before buying one.",
            "In the average lifetime, a person will walk the equivalent of 5 times around the equator.",
            "Koala is Aboriginal for \"no drink\".",
            "Shakespeare spelled his OWN name several different ways.",
            "The first contraceptive was crocodile dung used by the ancient Egyptians.",
            "A signature is called a John Hancock because he signed the Declaration of Independence. Only 2 people signed the declaration of independence on July 4. The Last person signed 2 years later.",
            "Arnold Schonberg suffered from triskaidecaphobia, the fear of the number 13.  He died at 13 minutes from midnight on Friday the 13th.",
            "Mozart wrote the nursery rhyme 'twinkle, twinkle, little star' at the age of 5.",
            "Weatherman Willard Scott was the first original Ronald McDonald. ",
            "Virginia Woolf wrote all her books standing.",
            "Einstein couldn't speak fluently until after his ninth birthday. His parents thought he was mentally retarded.",
            "Al Capone's business card said he was a used furniture dealer.",
            "Deborah Winger did the voice of E.T.",
            "Kelsey Grammar sings and plays the piano for the theme song of Fraiser.",
            "Thomas Edison, acclaimed inventor of the light bulb, was afraid of the dark.",
            "In England, the Speaker of the House is not allowed to speak.",
            "You can sail all the way around the world at latitude 60 degrees south.",
            "The earth weighs around 6,588,000,000,000,000,000,000,000,000 tons.",
            "Peanuts are one of the ingredients of dynamite.",
            "Porcupines can float in water.",
            "The average person's left hand does 56% of the typing.",
            "A shark is the only fish that can blink with both eyes.",
            "The longest one-syllable word in the English language is \"screeched.\"",
            "All of the clocks in the movie \"Pulp Fiction\" are stuck on 4: 20, a national pot-smokers hour.",
            "\"Dreamt\" is the only English word that ends in the letters \"mt.\"",
            "Almonds are a member of the peach family.",
            "Winston Churchill was born in a ladies' room during a dance.",
            "Maine is the only state whose name is just one syllable.",
            "There are only four words in the English language which end in \"dous\": tremendous, horrendous, stupendous, and  hazardous.",
            "Tigers not only have striped fur, they have striped skin!",
            "In most advertisements, including newspapers, the time displayed on a watch is 10:10.",
            "On the ground, a group of geese is a gaggle, in the sky it is a skein.",
            "To Ensure Promptness, one is expected to pay beyond the value of service – hence the later abbreviation: T.I.P.",
            "When the University of Nebraska Cornhuskers play football at home, the stadium becomes the state's third largest city.",
            "The characters Bert and Ernie on Sesame Street were named after Bert the cop and Ernie the taxi driver in Frank Capra\\'s \"Its A Wonderful Life.\"",
            "A dragonfly has a lifespan of 24 hours.",
            "A dime has 118 ridges around the edge.",
            "On an American one-dollar bill, there is an owl in the upper left-hand corner of the \"1\"encased in the \"shield\" and a spider hidden in the front upper right-hand corner.",
            "The name for Oz in the \"Wizard of Oz\" was thought up when the creator, Frank Baum, looked at his filing cabinet and saw A-N, and O-Z; hence the name \"OZ.\"",
            "The microwave was invented after a researcher walked by a radar tube and a chocolate bar melted in his pocket.",
            "Mr. Rogers is an ordained minister.",
            "John Lennon's first girlfriend was named Thelma Pickles.",
            "There are 336 dimples on a regulation golf ball.",
            "The scene where Indiana Jones shoots the swordsman in Raider’s of the Lost Ark was Harrison Ford's idea so that he could take a bathroom break.",
            "A crocodile cannot stick its tongue out.",
            "A snail can sleep for three years.",
            "All polar bears are left-handed.",
            "China has more English speakers than the United States.",
            "Elephants are the only animals that can't jump.",
            "February 1865 is the only month in recorded history not to have a full moon.",
            "If the population of China walked past you in single file, the line would never end because of the rate of reproduction.",
            "If you yelled for 8 years,7 months and 6 days, you will have produced enough sound energy to heat one cup of coffee.",
            "In the last 4000 years, no new animals have been domesticated.",
            "Leonardo Da Vinci invented the scissors.",
            "The word \"set\" has more definitions than any other word in the English language.",
            "Nutmeg is extremely poisonous if injected intravenously.",
            "On average, people fear spiders more than they do death.",
            "One of the reasons marijuana is illegal today is because cotton growers in the 1930s lobbied against hemp farmers they saw it as competition.",
            "Shakespeare invented the word 'assassination' and 'bump'.",
            "Some lions mate over 50 times a day.",
            "Starfish haven't got brains.",
            "The ant always falls over on its right side when intoxicated.",
            "The name of all continents in the world end with the same letter that they start with.",
            "There are two credit cards for every person in the United States.",
            "The longest word comprised of one row on the keyboard is: TYPEWRITER",
            "You can't kill yourself by holding your breath.  ",
            "The average person spends 12 weeks a year 'looking for things'.",
            "The symbol on the \"pound\" key (#) is called an octothorpe..  ",
            "The dot over the letter 'i' is called a tittle.  ",
            "Ingrown toenails are hereditary.  ",
            "\"Underground\" is the only word in the English language that begins and ends with the letters \"und\"",
            "The longest word in the English language, according to the Oxford English Dictionary, is: pneumonoultramicroscopicsilicovolcanoconiosis..  ",
            "The longest place-name still in use is: Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiakitnatahu, a New Zealand hill.  ",
            "An ostrich's eye is bigger than its brain.  ",
            "Alfred Hitchcock didn't have a belly button. It was eliminated when he was sewn up after surgery.",
            "Telly Savalas and Louis Armstrong died on their birthdays.  ",
            "Donald Duck's middle name is Fauntleroy.  ",
            "The muzzle of a lion is like a fingerprint - no two lions have the same pattern of whiskers.  ",
            "Steely Dan got their name from a sexual device depicted in the book 'The Naked Lunch'.  ",
            "The Ramses brand condom is named after the great pharoh Ramses II who fathered over 160 children.",
            "There is a seven letter word in the English language that contains ten words without rearranging any of its letters,\"therein\": the, there, he, in, rein, her, here, ere, therein, herein.  ",
            "A goldfish has a memory span of three seconds.  ",
            "Cranberries are sorted for ripeness by bouncing them; a fully ripened cranberry can be dribbled like a basketball.  ",
            "The male gypsy moth can \"smell\" the virgin female gypsy moth from 1.8 miles away.  ",
            "The letters KGB stand for Komitet Gosudarstvennoy Bezopasnosti.  ",
            "The word \"dexter\" whose meaning refers to the right hand is typed with only the left hand.  ",
            "To \"testify\" was based on men in the Roman court swearing to a statement made by swearing on their testicles.  ",
            "Facetious and abstemious contain all the vowels in the correct order, as does arsenious, meaning \"containing arsenic.\"  ",
            "The word \"Checkmate\" in chess comes from the Persian phrase \"Shah Mat,\" which means \"the king is dead.\"",
            "The first episode of \"Joanie Loves Chachi\" was the highest rated American program in the history of Korean television, a country where \"Chachi\" translates to \"penis\".  ",
            "Rubber bands last longer when refrigerated.  ",
            "The national anthem of Greece has 158 verseson their eyes!",
            "A jellyfish is 95 percent water!",
            "In Bangladesh, kids as young as 15 can be jailed for cheating on their finals!",
            "The katydid bug hears through holes in its hind legs!",
            "Q is the only letter in the alphabet that does not appear in the name of any of the United States!",
            "166,875,000,000 pieces of mail are delivered each year in the US",
            "Bats always turn left when exiting a cave",
            "The praying mantis is the only insect that can turn its head",
            "Daffy Duck\\'s middle name is \"Dumas\"",
            "In Disney\\'s Fantasia, the Sorcerer\\'s name is \"Yensid\" (Disney backwards.)",
            "In The Empire Strikes Back there is a potato hidden in the asteroid field",
            "Walt Disney holds the world record for the most Academy Awards won by one person, he has won twenty statuettes, and twelve other plaques and certificates",
            "James Bond's car had three different license plates in Goldfinger",
            "Canada makes up 6.67 percent of the Earth's land area",
            "South Dakota is the only U.S state which shares no letters with the name of it's capital",
            "The KGB is headquartered at No. 2 Felix Dzerzhinsky Square, Moscow",
            "The Vatican city registered 0 births in 1983",
            "Spain leads the world in cork production",
            "There are 1,792 steps in the Eiffel Tower",
            "There are 269 steps to the top of the Leaning Tower of Pisa",
            "Leonardo da Vinci could write with one hand while drawing with the other"
        ]
    }
    return random.choice(infos.get("lista"))


RANDOM = [
    "Flamingos can only eat with their heads upside down.\n\nThese tall pink characters use their tongue as a sieve to catch food by flipping their heads about. The flamingo’s tongue helps pump the food-filled water in and out of their mouths about three times a second. This technique is called filter feeding! ",
    "A blob of toothpaste is called a nurdle.\n\nNobody is quite sure where the word 'nurdle' originated. A fact as useless as the word.",
    "The moon has moonquakes.\n\nShallow moonquakes are caused when the moon's crust slips and cracks due to the gradual shrinking of the moon when it cools. Meteors can also cause quakes when they crash into the surface of the moon.",
    "People used to believe that kissing a donkey could relieve a toothache.\n\nYep, that’s right!  People have always done rather odd things to prevent toothache. For example, the Ancient Egyptians scrubbed their teeth with a powder made from ox hooves and eggshells. But weirder still, during the Middle Ages in Germany, they thought a cure for a toothache was kissing a donkey. Even if it did something for your toothache, it certainly won't do anything for your breath.",
    "If you open your eyes in a pitch-black room, the colour you'll see is called 'eigengrau'.\n\n‘Eigengrau’ is German for ‘intrinsic grey’, also known as dark light, or brain grey. It is used to describe the uniform dark grey background that many people see in the absence of light. The term dates back to the nineteenth century.",
    "Rabbits can’t vomit.\n\nWelcome to the vomit void. Bunny rabbits are very hygienic creatures who self-groom in much the same way that a cat does. But the rabbit’s digestive system does not move in reverse, meaning rabbits cannot bring up hairballs like a cat can. So basically if you're banking on a burst of bunny barf, don't hold your breath.",
    "Alfred Hitchcock didn’t have a bellybutton.\n\nThe famous director of The Birds and Rear Window was born with one, but after surgery, it vanished after he was sewn back up! ",
    "Bees sometimes sting other bees.\n\nThey don't mean to, but sometimes when they try to defend their nests from intruders, they accidentally sting other bees. Ouch!",
    "There are 32 muscles in a cat’s ear.\n\nThis feature is what allows cats to swivel and rotate their ears so that they can pinpoint the source of a noise. But what's more incredible is that they can move each ear independently and rotate them 180 degrees!",
    "There are more chickens in England than people.\n\nThere are around 982 million chickens eaten each year in the U.K. by 66 million people...  this statistic means that should the chickens decide to take over the country, (a la Jurassic Park) we would be massively outnumbered. The threat is real, people. Come the chicken uprising don't say we didn't warn you.",
    "Crows hold grudges.\n\nA 2011 study revealed crows can remember the human faces of those who capture them. According to another study, ravens, including crows, jays and magpies, can 'hold grudges' for up to two years. So make sure you don't upset a crow, because they just won't let it lie!",
    "‘Hippopotomonstrosesquippedaliophobia' is a fear of long words.",
    "Due to a genetic defect, cats can’t taste sweet things.\n\nThis is because they are missing a taste receptor gene that allows their brains to recognise sweet tastes. No wonder they're often grumpy!",
    "Tornadoes can make it ‘rain’ fish.\n\nThis phenomenon usually happens when swirling whirlwinds over shallow water develop into waterspouts that suck up water and the things living in it, like frogs, eels and fish. The creatures are carried long distances by clouds, and then drop to the ground like a mic.",
]
